### PR TITLE
Adding feature Dissimilarity.

### PR DESCRIPTION
**Pull request by jcfaracco**
This is just a new feature being added to support the parity with scikit image. This PR just implements a simple feature called Dissimilarity. Its equation was added into the documents also.

### CODE REVIEW

**Comment by jcfaracco** [comment]
@Eve-ning sorry to bother you again. Is there any section explaining how can I test it locally before submitting a PR?

**Comment by jcfaracco** [comment]
A v2 was sent to change `Enum` to `IntEnum`.

**Comment by Eve-ning** [comment]
The PR generally looks fine, I'll take a closer look in a few

> @Eve-ning sorry to bother you again. Is there any section explaining how can I test it locally before submitting a PR? 
Running the integration tests should be fine.
Since you've added dissimilarity, there 2 tests needed
1) Checking consistency between CuPy & Pure Python
    - Implementing (dissimilarity) it in pure Python
    - Implementing (dissimilarity) it in CuPy
    - Testing if they are consistent across random inputs
2) Checking consistency across runs
    - If 1) passes, then export the current result as a pickle `.pkl`
    - Check if the result changes across runs, it shouldn't (too much)

not sure if there's a more robust way to do this

> Btw, we should also enable tests for PRs hehe
not sure if there's another way to integrate testing since the environment depends on `cupy`

> If there is not, we should include some Contribution Guidelines into the README.md
initially didn't expect this project to get traction, I'll add a contribution guideline some time

**Comment by Eve-ning** [comment]
@jcfaracco I've added 2 MRs on your fork, should be good to go after you've checked & merged them.

**Comment by Eve-ning** [comment]
will be away till the 22-23, will do one last check and this should be good to go

**Comment by jcfaracco** [comment]
@Eve-ning don't worry. 😃

**Comment by Eve-ning** [comment]
Note: Minor afterfix to the NumPy array as it was cached with the unnormalized Dissimilarity Feature

**Pull request merged**
